# =============================================================================
# deployment.yaml
# =============================================================================
app:
  name: web
  replicas: 2
image:
  repository: ghcr.io/jian11442/joytify-web
  tag: a237780f75fff2a6b2419b9acc4076d9c9844f14
  digest: "sha256:20b3fbcd61b12853aac4953ef29c16c6f5c342d6b2ebdc75eba0c7e0c0d5ff44"
imagePullSecrets:
  name: ghcr-secret # *
container:
  name: web-container
  port: 5173 # *
strategy:
  maxUnavailable: 1
  maxSurge: 1
# =============================================================================
# service.yaml
# =============================================================================
service:
  name: web-service # *
  type: ClusterIP
  port: 5173 # *
  targetPort: 5173 # *
# =============================================================================
# ingress.yaml
# =============================================================================
ingress:
  enabled: true
  domain: "139.59.223.77.nip.io" # *
  clusterIssuer: "letsencrypt-staging" # *
