# =============================================================================
# deployment.yaml
# =============================================================================
app:
  name: web
  replicas: 2
image:
  repository: ghcr.io/jian11442/joytify-web
  tag: 89501c4dca29df8c2c048bbeb8fd75eb51a07d5b
  digest: "sha256:e31d6efaab4280bc740a88a534dd7b09572342049085f9e84b0e990694d3e247"
imagePullSecrets:
  name: ghcr-secret # *
container:
  name: web-container
  port: 5173 # *
strategy:
  maxUnavailable: 1
  maxSurge: 1
# =============================================================================
# service.yaml
# =============================================================================
service:
  name: web-service # *
  type: ClusterIP
  port: 5173 # *
  targetPort: 5173 # *
# =============================================================================
# ingress.yaml
# =============================================================================
ingress:
  enabled: true
  domain: "146.190.193.154.nip.io" # *
  clusterIssuer: "letsencrypt-staging" # *
