# =============================================================================
# deployment.yaml
# =============================================================================
app:
  name: web
  replicas: 2
image:
  repository: ghcr.io/jian11442/joytify-web
  tag: 5a940c758c1f79bcff57705480a93a9593647bc8
  digest: "sha256:4784c289be67ce29445ebc42770f1f012fe2b0d6e2c6f0f34ddfc9cd87be0a6a"
imagePullSecrets:
  name: ghcr-secret # *
container:
  name: web-container
  port: 5173 # *
strategy:
  maxUnavailable: 1
  maxSurge: 1
# =============================================================================
# service.yaml
# =============================================================================
service:
  name: web-service # *
  type: ClusterIP
  port: 5173 # *
  targetPort: 5173 # *
# =============================================================================
# ingress.yaml
# =============================================================================
ingress:
  enabled: true
  domain: "146.190.193.154.nip.io" # *
  clusterIssuer: "letsencrypt-staging" # *
