# =============================================================================
# deployment.yaml
# =============================================================================
app:
  name: web
  replicas: 2
image:
  repository: ghcr.io/jian11442/joytify-web
  tag: cd7df8e02ae5f531168a56f0bca2deec36c31f69
  digest: "sha256:3cec8277b4913ed7c2e00e4da8b4031ad312e995c3cc6b984cfc01a56616405f"
imagePullSecrets:
  name: ghcr-secret # *
container:
  name: web-container
  port: 5173 # *
strategy:
  maxUnavailable: 1
  maxSurge: 1
# =============================================================================
# service.yaml
# =============================================================================
service:
  name: web-service # *
  type: ClusterIP
  port: 5173 # *
  targetPort: 5173 # *
# =============================================================================
# ingress.yaml
# =============================================================================
ingress:
  enabled: true
  domain: "146.190.193.154.nip.io" # *
  clusterIssuer: "letsencrypt-staging" # *
