# =============================================================================
# deployment.yaml
# =============================================================================
app:
  name: web
  replicas: 2
image:
  repository: ghcr.io/jian11442/joytify-web
  tag: c187670e3d5d5e4e829d305e646d52059dabbebe
  digest: "sha256:c05f43e71bbee534ecb1452ffe2291a1346f5953698dd899b85393ca6a3a654d"
imagePullSecrets:
  name: ghcr-secret # *
container:
  name: web-container
  port: 5173 # *
strategy:
  maxUnavailable: 1
  maxSurge: 1
# =============================================================================
# service.yaml
# =============================================================================
service:
  name: web-service # *
  type: ClusterIP
  port: 5173 # *
  targetPort: 5173 # *
# =============================================================================
# ingress.yaml
# =============================================================================
ingress:
  enabled: true
  domain: "146.190.193.154.nip.io" # *
  clusterIssuer: "letsencrypt-staging" # *
